### ISSUE TITLE
Add mobs death without players being involved

### ISSUE THREAD

**Issue by Resoluciones** [TrollyLoki/SimpleDeathMessage#1]
Hi, great plugin!

Would it be possible you add message configuration for other entities (mobs, animals, villagers) also, when they are killed by other means without players being involved? (despawned by other plugins, killed by wither, death by suffocation, etc)

Thanks!!!!

**Comment by Resoluciones** [comment]
Great!  Here you can find a plugin that does that, but it is not configurable and also it is not working for some mobs for any reason (it's very old):  https://dev.bukkit.org/projects/equaldeath

Thanks!!!

**Comment by TrollyLoki** [comment]
I have looked at the code of the EqualDeath plugin and I now believe that it may be possible to show the death messages. If it is you can expect that I may add that functionality in the next update (1.2) P. S. The reason it doesn't work for some mobs is that the author of the plugin had a list of mobs in the code that did not include everyone.

**Comment by TrollyLoki** [comment]
I believe I am very close to finishing this feature. You can expect a release tonight or if not sometime tomorrow.

**Comment by TrollyLoki** [comment]
This feature has been added. The option for messages when mobs are killed by players has also been added. If you run into any problems or other minor issues feel free to tell me about them. Thanks for downloading my plugin 😄
